version: "3.8"

networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest #image
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # volume 지정
    ports:
      - 9090:9090 # port 지정
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini # grafana.ini 파일 ( 디폴트 값 )
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus
    networks:
      - monitor-net

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
    networks:
      - monitor-net